# This file is part of NPFL139 <http://github.com/ufal/npfl139/>.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
import warnings

import numpy as np
import torch


def typed_torch_function(device, *types, via_np=False):
    """Typed Torch function decorator.

    The positional input arguments are converted to torch Tensors of the given
    types and on the given device; for NumPy arrays on the same device,
    the conversion should not copy the data.

    The torch Tensors generated by the wrapped function are converted back
    to Numpy arrays before returning (while keeping original tuples, lists,
    and dictionaries).

    If casting an argument to a non-floating-point target dtype drops a non-zero
    fractional part (i.e. the casted values, viewed as floats, no longer equal
    the original values), a warning is emitted.
    """
    def check_typed_torch_function(wrapped, args):
        if len(types) != len(args):
            while hasattr(wrapped, "__wrapped__"):
                wrapped = wrapped.__wrapped__
            raise AssertionError("The typed_torch_function decorator for {} expected {} arguments, but got {}".format(
                wrapped, len(types), len(args)))

    def structural_map(value):
        if isinstance(value, torch.Tensor):
            return value.numpy(force=True)
        if isinstance(value, tuple):
            return tuple(structural_map(element) for element in value)
        if isinstance(value, list):
            return [structural_map(element) for element in value]
        if isinstance(value, dict):
            return {key: structural_map(element) for key, element in value.items()}
        return value

    def convert_arg(arg, typ, index, wrapped):
        source = np.asarray(arg) if via_np else arg
        casted = torch.as_tensor(source, dtype=typ, device=device)
        # If the target dtype is non-floating (integer or bool), check whether
        # the input held a fractional part that was silently truncated.
        if not casted.is_floating_point() and not casted.is_complex():
            source_known_integer = (
                (isinstance(source, torch.Tensor)
                 and not source.is_floating_point()
                 and not source.is_complex())
                or (isinstance(source, np.ndarray)
                    and not np.issubdtype(source.dtype, np.floating)
                    and not np.issubdtype(source.dtype, np.complexfloating))
            )
            if not source_known_integer:
                try:
                    reference = torch.as_tensor(source, dtype=torch.float64, device=device)
                except (TypeError, RuntimeError, ValueError):
                    reference = None
                if reference is not None and not torch.equal(reference, casted.to(torch.float64)):
                    while hasattr(wrapped, "__wrapped__"):
                        wrapped = wrapped.__wrapped__
                    warnings.warn(
                        "typed_torch_function for {}: argument #{} was cast to {} from a "
                        "non-integer numeric input; the fractional part was lost.".format(
                            wrapped, index, typ),
                        stacklevel=3,
                    )
        return casted

    class TypedTorchFunctionWrapper:
        def __init__(self, func):
            self.__wrapped__ = func

        def __call__(self, *args, **kwargs):
            check_typed_torch_function(self.__wrapped__, args)
            return structural_map(self.__wrapped__(
                *[convert_arg(arg, typ, index, self.__wrapped__)
                  for index, (arg, typ) in enumerate(zip(args, types))], **kwargs))

        def __get__(self, instance, cls):
            return TypedTorchFunctionWrapper(self.__wrapped__.__get__(instance, cls))

    return TypedTorchFunctionWrapper
